---
title: "Improving nutrition status for under 5 children in Zambezia and Nampula"
subtitle: "Difference-in-difference analysis results"
author: 
  - name: Mark Myatt
  - name: Ernest Guevarra
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_depth: 3
    self_contained: true
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  echo = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.path = here::here("outputs/figures/")
)

suppressPackageStartupMessages(source("packages.R"))
for (f in list.files(here::here("R"), full.names = TRUE)) source (f)

targets::tar_load(c(diff_in_diff_table, diff_in_diff_table_long))


water_ladder <- c("#4575b4", "#74add1", "#ffffbf", "#feb24c", "#ec7014")
sanitation_ladder <- c("#1a9850", "#a6d96a", "#ffffbf", "#feb24c", "#ec7014")
hygiene_ladder <- c("#cab2d6", "#feb24c", "#ec7014")
bmi_classes <- c("#d7191c", "#fdae61", "#abdda4", "#2b83ba")

theme_mozambique <- theme_bw() + 
  theme(
    plot.title = element_text(size = 14),
    plot.subtitle = element_text(size = 12),
    panel.border = element_rect(size = 0.5, colour = "gray70"),
    panel.grid.major = element_line(
      linetype = 1, size = 0.2, colour = "gray90"
    ),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(size = 12, hjust = 0),
    legend.key = element_rect(linetype = 0),
    axis.line.x = element_line(size = 1, colour = "gray70"),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    axis.ticks = element_line(colour = "gray70", size = 0.5)
  )
```

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

<br/>

## Child anthropometry

### Child stunting

```{r stunting, fig.align = "center", fig.width = 10}
diff_in_diff_table_long |>
  subset(
    indicator_variable %in% c(
      "global_stunting", "moderate_stunting", "severe_stunting"
    ),
    select = c(
      strata, indicator_label, indicator_category, estimate, se, lcl, ucl, z, p
    )
  ) |>
  dplyr::mutate(
    category = factor(
      indicator_category, 
      levels = c("Global stunting", "Moderate stunting", "Severe stunting"),
      labels = c("Global", "Moderate", "Severe")
    ),
    change_class = ifelse(estimate > 0, "increase", "decrease"),
    y_adjust = ifelse(estimate > 0, -0.3, 0.3)
  ) |>
  ggplot(
    mapping = aes(
      x = category, y = estimate * 100, fill = change_class, group = strata
    )
  ) +
  geom_bar(stat = "identity") +
  geom_text(
    mapping = aes(
      x = category, y = y_adjust,
      label = paste0("p-value: ", round(p, digits = 4))
    ),
    fontface = "italic", size = 2
  ) +
  scale_fill_manual(name = "", values = alpha(c("#4575b4", "#d73027"), 0.6)) +
  scale_y_continuous(
    limits = c(-2, 8), breaks = seq(from = -2, to = 8, by = 2)
  ) +
  labs(
    title = "Change in child stunting",
    subtitle = "Difference-in-difference in child stunting estimates in Zambézia, Nampula and Overall",
    x = "", y = "%"
  ) +
  facet_wrap(~ strata, ncol = 3) + 
  theme_mozambique
```

### Child underweight

```{r underweight, fig.align = "center", fig.width = 10}
diff_in_diff_table_long |>
  subset(
    indicator_variable %in% c(
      "global_underweight", "moderate_underweight", "severe_underweight"
    ),
    select = c(
      strata, indicator_label, indicator_category, estimate, se, lcl, ucl, z, p
    )
  ) |>
  dplyr::mutate(
    category = factor(
      indicator_category, 
      levels = c("Global underweight", "Moderate underweight", "Severe underweight"),
      labels = c("Global", "Moderate", "Severe")
    ),
    change_class = ifelse(estimate > 0, "increase", "decrease"),
    y_adjust = ifelse(estimate > 0, -0.3, 0.3)
  ) |>
  ggplot(
    mapping = aes(
      x = category, y = estimate * 100, fill = change_class, group = strata
    )
  ) +
  geom_bar(stat = "identity") +
  geom_text(
    mapping = aes(
      x = category, y = y_adjust, 
      label = paste0("p-value: ", round(p, digits = 4))
    ),
    fontface = "italic", size = 2
  ) +
  scale_fill_manual(name = "", values = alpha(c("#4575b4", "#d73027"), 0.6)) +
  scale_y_continuous(
    limits = c(-4, 6), breaks = seq(from = -4, to = 6, by = 2)
  ) +
  labs(
    title = "Change in child underweight",
    subtitle = "Difference-in-difference in child underweight estimates in Zambézia, Nampula and Overall",
    x = "", y = "%"
  ) +
  facet_wrap(~ strata, ncol = 3) + 
  theme_mozambique
```

### Child wasting by weight-for-height

```{r wasting-whz, fig.align = "center", fig.width = 10}
diff_in_diff_table_long |>
  subset(
    indicator_variable %in% c(
      "global_wasting_by_weight_for_height", 
      "moderate_wasting_by_weight_for_height",
      "severe_wasting_by_weight_for_height"
    ),
    select = c(
      strata, indicator_label, indicator_category, estimate, se, lcl, ucl, z, p
    )
  ) |>
  dplyr::mutate(
    category = factor(
      indicator_category, 
      levels = c("Global wasting", "Moderate wasting", "Severe wasting"),
      labels = c("Global", "Moderate", "Severe")
    ),
    change_class = ifelse(estimate > 0, "increase", "decrease"),
    y_adjust = ifelse(estimate > 0, -0.2, 0.2)
  ) |>
  ggplot(
    mapping = aes(
      x = category, y = estimate * 100, fill = change_class, group = strata
    )
  ) +
  geom_bar(stat = "identity") +
  geom_text(
    mapping = aes(
      x = category, y = y_adjust, 
      label = paste0("p-value: ", round(p, digits = 4))
    ),
    fontface = "italic", size = 2
  ) +
  scale_fill_manual(name = "", values = alpha(c("#4575b4", "#d73027"), 0.6)) +
  scale_y_continuous(
    limits = c(-6, 2), breaks = seq(from = -6, to = 2, by = 2)
  ) +
  labs(
    title = "Change in child wasting by weight-for-height",
    subtitle = "Difference-in-difference in child wasting by weight-for-height estimates in Zambézia, Nampula and Overall",
    x = "", y = "%"
  ) +
  facet_wrap(~ strata, ncol = 3) + 
  theme_mozambique
```

### Child wasting by MUAC

```{r wasting-muac, fig.align = "center", fig.width = 10}
diff_in_diff_table_long |>
  subset(
    indicator_variable %in% c(
      "global_wasting_by_muac", 
      "moderate_wasting_by_muac",
      "severe_wasting_by_muac"
    ),
    select = c(
      strata, indicator_label, indicator_category, estimate, se, lcl, ucl, z, p
    )
  ) |>
  dplyr::mutate(
    category = factor(
      indicator_category, 
      levels = c("Global wasting", "Moderate wasting", "Severe wasting"),
      labels = c("Global", "Moderate", "Severe")
    ),
    change_class = ifelse(estimate > 0, "increase", "decrease"),
    y_adjust = ifelse(estimate > 0, -0.1, 0.1)
  ) |>
  ggplot(
    mapping = aes(
      x = category, y = estimate * 100, fill = change_class, group = strata
    )
  ) +
  geom_bar(stat = "identity") +
  geom_text(
    mapping = aes(
      x = category, y = y_adjust, 
      label = paste0("p-value: ", round(p, digits = 4))
    ),
    fontface = "italic", size = 2
  ) +
  scale_fill_manual(name = "", values = alpha(c("#4575b4", "#d73027"), 0.6)) +
  scale_y_continuous(
    limits = c(-2, 2), breaks = seq(from = -2, to = 2, by = 0.5)
  ) +
  labs(
    title = "Change in child wasting by MUAC",
    subtitle = "Difference-in-difference in child wasting by MUAC estimates in Zambézia, Nampula and Overall",
    x = "", y = "%"
  ) +
  facet_wrap(~ strata, ncol = 3) + 
  theme_mozambique
```

### Severe child wasting by oedema

```{r wasting-oedema, fig.align = "center", fig.width = 6}
diff_in_diff_table_long |>
  subset(
    indicator_variable == "severe_wasting_by_oedema",
    select = c(
      strata, indicator_label, indicator_category, estimate, se, lcl, ucl, z, p
    )
  ) |>
  dplyr::mutate(
    change_class = ifelse(estimate > 0, "increase", "decrease"),
    y_adjust = ifelse(estimate > 0, -0.02, 0.02)
  ) |>
  ggplot(
    mapping = aes(
      x = strata, y = estimate * 100, fill = change_class, group = strata
    )
  ) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(
    mapping = aes(
      x = strata, y = y_adjust, 
      label = paste0("p-value: ", round(p, digits = 4))
    ),
    fontface = "italic", size = 2
  ) +
  scale_fill_manual(name = "", values = alpha(c("#4575b4", "#d73027"), 0.6)) +
  scale_y_continuous(
    limits = c(-0.1, 0.5), breaks = seq(from = -0.1, to = 0.5, by = 0.1)
  ) +
  labs(
    title = "Change in severe child wasting by oedema",
    subtitle = "Difference-in-difference in severe child wasting by\noedema estimates in Zambézia, Nampula and Overall",
    x = "", y = "%"
  ) +
  theme_mozambique
```

## Infant and young child feeding

### Food groups consumption in the past 24 hours

```{r iycf, fig.align = "center", fig.width = 10, fig.height = 12}
diff_in_diff_table_long |>
  subset(
    indicator_label == "Food groups",
    select = c(
      strata, indicator_label, indicator_category, estimate, se, lcl, ucl, z, p
    )
  ) |>
    dplyr::mutate(
    change_class = ifelse(estimate > 0, "increase", "decrease"),
    y_adjust = ifelse(estimate > 0, -1.2, 1.2)
  ) |>
  ggplot(
    mapping = aes(
      x = strata, y = estimate * 100, fill = change_class, group = strata
    )
  ) +
  geom_bar(stat = "identity", width = 0.75) +
  geom_text(
    mapping = aes(
      x = strata, y = y_adjust, 
      label = paste0("p-value: ", round(p, digits = 4))
    ),
    fontface = "italic", size = 2
  ) +
  scale_fill_manual(name = "", values = alpha(rev(c("#4575b4", "#d73027")), 0.6)) +
  scale_y_continuous(
    limits = c(-25, 20), breaks = seq(from = -25, to = 20, by = 5)
  ) +
  labs(
    title = "Change in 24-hour food groups consumption",
    subtitle = "Difference-in-difference in 24-hour food groups consumption estimates in Zambézia, Nampula and Overall",
    x = "", y = "%"
  ) +
  facet_wrap(~ indicator_category, ncol = 2) +
  theme_mozambique
```

<br/>
<br/>
