---
title: "Improving nutrition status for under 5 children in Zambezia and Nampula"
subtitle: "Endline survey food security indicator results"
author: 
    - name: Mark Myatt
    - name: Ernest Guevarra
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_depth: 3
    self_contained: true
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  echo = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.path = here::here("outputs/figures/")
)

suppressPackageStartupMessages(source("packages.R"))
for (f in list.files(here::here("R"), full.names = TRUE)) source (f)

targets::tar_load(dplyr::starts_with("endline"))

water_ladder <- c("#4575b4", "#74add1", "#ffffbf", "#feb24c", "#ec7014")
sanitation_ladder <- c("#1a9850", "#a6d96a", "#ffffbf", "#feb24c", "#ec7014")
hygiene_ladder <- c("#cab2d6", "#feb24c", "#ec7014")
bmi_classes <- c("#d7191c", "#fdae61", "#abdda4", "#2b83ba")
fcs_classes <- c("#d73027", "#ffffbf", "#4575b4")
rcsi_classes <- c("#d73027", "#ffffbf", "#4575b4")
lcsi_classes <- c("#d73027", "#fc8d59", "#ffffbf", "#4575b4")
stock_classes <- c("gray70", "#a1dab4", "#41b6c4", "#2c7fb8", "#253494")

theme_mozambique <- theme_bw() + 
  theme(
    plot.title = element_text(size = 14),
    plot.subtitle = element_text(size = 12),
    panel.border = element_rect(size = 0.5, colour = "gray70"),
    panel.grid.major = element_line(
      linetype = 1, size = 0.2, colour = "gray90"
    ),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(size = 12, hjust = 0),
    legend.key = element_rect(linetype = 0),
    axis.line.x = element_line(size = 1, colour = "gray70"),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    axis.ticks = element_line(colour = "gray70", size = 0.5)
  )
```

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

<br/>

## Household dietary diversity score

```{r hdds, echo = FALSE}
hdds_province_overall <- endline_hdds_province_table |>
  subset(
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

hdds_strata <- endline_hdds_strata_table |>
  subset(
    strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

hdds_study_group <- endline_hdds_study_group_table |>
  subset(
    study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   hdds_province_overall,
#   hdds_strata,
#   hdds_study_group
# ) |>
rbind(
  hdds_province_overall,
  hdds_strata
) |>
  #(\(x) x[ , c(1, 2, 6, 10, 3, 7, 11, 4, 8, 12, 5, 9, 13)])() |>
  (\(x)
    {
      x[ , 2:4]  <- round(x[ , 2:4], digits = 3)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", c("Estimate", "95% LCL", "95% UCL")),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = FALSE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Mean Household Dietary Diversity Score" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

## Food consumption score

```{r fcs, echo = FALSE}
fcs_province_overall <- endline_fcs_province_table |>
  subset(
    indicator_variable == "fcs_score",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

fcs_strata <- endline_fcs_strata_table |>
  subset(
    indicator_variable == "fcs_score" & strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

fcs_study_group <- endline_fcs_study_group_table |>
  subset(
    indicator_variable == "fcs_score" & study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   fcs_province_overall,
#   fcs_strata,
#   fcs_study_group
# ) |>
rbind(
  fcs_province_overall,
  fcs_strata
) |>
  #(\(x) x[ , c(1, 2, 6, 10, 3, 7, 11, 4, 8, 12, 5, 9, 13)])() |>
  (\(x)
    {
      x[ , 2:4]  <- round(x[ , 2:4], digits = 3)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", c("Estimate", "95% LCL", "95% UCL")),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = FALSE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Mean Food Consumption Score" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

<br/>

```{r fcs_province_plot, echo = FALSE, fig.align = "center", fig.width = 10}
endline_fcs_province_table |>
  subset(
    indicator_category != "Mean"
  ) |>
  dplyr::mutate(
    indicator_category = factor(
      x = indicator_category, levels = rev(c("poor", "borderline", "acceptable"))
    ),
    strata = factor(
      x = strata, levels = c("Zambézia", "Nampula", "Overall")
    )
  ) |>
  ggplot(mapping = aes(x = strata, y = estimate * 100, fill = indicator_category)) +
  geom_bar(stat = "identity", position = "stack", width = 0.5) +
  scale_fill_manual(name = "", values = alpha(rev(fcs_classes), 0.6)) +
  labs(
    title = "Food insecurity status based on food consumption score",
    subtitle = "Proportion of households in Zambézia, Nampula, and overall by food consumption score food insecurity categories",
    x = "", y = "%"
  ) +
  #facet_wrap(~strata, scales = "free_y") +
  theme_mozambique
```

```{r fcs_strata_plot, echo = FALSE, fig.align = "center", fig.width = 10}
endline_fcs_strata_table |>
  subset(strata != "Overall" & indicator_category != "Mean") |>
  dplyr::mutate(
    province = ifelse(
      strata %in% c("Monapo", "Nacala-A-Velha", "Ribáuè", "Rest of Nampula"),
      "Nampula", "Zambézia"
    ) |>
      factor(levels = c("Zambézia", "Nampula")),
    strata = factor(
      strata,
      levels = c(
        "Gurúè", "Lugela", "Pebane", "Molumbo", "Rest of Zambézia", 
        "Monapo", "Nacala-A-Velha", "Ribáuè", "Rest of Nampula"
      ),
      labels = c(
        "\nGurúè", "\nLugela", "\nPebane", "\nMolumbo", "Rest of\nZambézia", 
        "\nMonapo", "\nNacala-A-Velha", "\nRibáuè", "Rest of\nNampula"
      )
    ),
    indicator_category = factor(
      x = indicator_category, levels = rev(c("poor", "borderline", "acceptable"))
    ),
  ) |>
  ggplot(
    mapping = aes(x = strata, y = estimate * 100, fill = indicator_category)
  ) +
  geom_bar(stat = "identity", position = "stack", width = 0.75) +
  scale_fill_manual(name = "", values = alpha(rev(fcs_classes), 0.6)) +
  labs(
    title = "Food insecurity status based on food consumption score",
    subtitle = "Proportion of households Zambézia and Nampula districts by food consumption score food insecurity categories",
    x = "", y = "%"
  ) +
  facet_wrap(~province, scales = "free_x") +
  theme_mozambique
```

<br/>

```{r fcs_class, echo = FALSE}
fcs_province_overall <- endline_fcs_province_table |>
  subset(
    indicator_variable != "fcs_score",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

fcs_strata <- endline_fcs_strata_table |>
  subset(
    indicator_variable != "fcs_score" & strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

fcs_study_group <- endline_fcs_study_group_table |>
  subset(
    indicator_variable != "fcs_score" & study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   fcs_province_overall,
#   fcs_strata,
#   fcs_study_group
# ) |>
rbind(
  fcs_province_overall,
  fcs_strata
) |>
  (\(x) x[ , c(1, 2, 5, 8, 3, 6, 9, 4, 7, 10)])() |>
  (\(x)
    {
      x[ , 2:10]  <- round(x[ , 2:10] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Estimate", "95% LCL", "95% UCL"), 3)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Poor" = 3,
      "Borderline" = 3,
      "Acceptable" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

## Reduced coping strategies index

```{r rcsi, echo = FALSE}
rcsi_province_overall <- endline_rcsi_province_table |>
  subset(
    indicator_variable == "rcsi_score",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

rcsi_strata <- endline_rcsi_strata_table |>
  subset(
    indicator_variable == "rcsi_score" & strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

rcsi_study_group <- endline_rcsi_study_group_table |>
  subset(
    indicator_variable == "rcsi_score" & study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   rcsi_province_overall,
#   rcsi_strata,
#   rcsi_study_group
# ) |>
rbind(
  rcsi_province_overall,
  rcsi_strata
) |>
  #(\(x) x[ , c(1, 2, 6, 10, 3, 7, 11, 4, 8, 12, 5, 9, 13)])() |>
  (\(x)
    {
      x[ , 2:4]  <- round(x[ , 2:4], digits = 3)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", c("Estimate", "95% LCL", "95% UCL")),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = FALSE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Mean Reduced Coping Strategies Index" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

<br/>

```{r rcsi_province_plot, echo = FALSE, fig.align = "center", fig.width = 10}
endline_rcsi_province_table |>
  subset(
    indicator_category != "Mean"
  ) |>
  dplyr::mutate(
    indicator_category = factor(
      x = indicator_category, levels = c("minimal", "stressed", "crisis")
    ),
    strata = factor(
      x = strata, levels = c("Zambézia", "Nampula", "Overall")
    )
  ) |>
  ggplot(mapping = aes(x = strata, y = estimate * 100, fill = indicator_category)) +
  geom_bar(stat = "identity", position = "stack", width = 0.5) +
  scale_fill_manual(name = "", values = alpha(rev(rcsi_classes), 0.6)) +
  labs(
    title = "Food insecurity status based on reduced coping strategies index",
    subtitle = "Proportion of households in Zambézia, Nampula, and overall by reduced coping strategies index food insecurity categories",
    x = "", y = "%"
  ) +
  theme_mozambique
```

```{r rcsi_strata_plot, echo = FALSE, fig.align = "center", fig.width = 10}
endline_rcsi_strata_table |>
  subset(strata != "Overall" & indicator_category != "Mean") |>
  dplyr::mutate(
    province = ifelse(
      strata %in% c("Monapo", "Nacala-A-Velha", "Ribáuè", "Rest of Nampula"),
      "Nampula", "Zambézia"
    ) |>
      factor(levels = c("Zambézia", "Nampula")),
    strata = factor(
      strata,
      levels = c(
        "Gurúè", "Lugela", "Pebane", "Molumbo", "Rest of Zambézia", 
        "Monapo", "Nacala-A-Velha", "Ribáuè", "Rest of Nampula"
      ),
      labels = c(
        "\nGurúè", "\nLugela", "\nPebane", "\nMolumbo", "Rest of\nZambézia", 
        "\nMonapo", "\nNacala-A-Velha", "\nRibáuè", "Rest of\nNampula"
      )
    ),
    indicator_category = factor(
      x = indicator_category, levels = c("minimal", "stressed", "crisis")
    ),
  ) |>
  ggplot(
    mapping = aes(x = strata, y = estimate * 100, fill = indicator_category)
  ) +
  geom_bar(stat = "identity", position = "stack", width = 0.75) +
  scale_fill_manual(name = "", values = alpha(rev(rcsi_classes), 0.6)) +
  labs(
    title = "Food insecurity status based on reduced coping strategies index",
    subtitle = "Proportion of households in Zambézia and Nampula districts by reduced coping strategies index food insecurity categories",
    x = "", y = "%"
  ) +
  facet_wrap(~province, scales = "free_x") +
  theme_mozambique
```

<br/>

```{r rcsi_class, echo = FALSE}
rcsi_province_overall <- endline_rcsi_province_table |>
  subset(
    indicator_variable != "rcsi_score",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

rcsi_strata <- endline_rcsi_strata_table |>
  subset(
    indicator_variable != "rcsi_score" & strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

rcsi_study_group <- endline_rcsi_study_group_table |>
  subset(
    indicator_variable != "rcsi_score" & study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   rcsi_province_overall,
#   rcsi_strata,
#   rcsi_study_group
# ) |>
rbind(
  rcsi_province_overall,
  rcsi_strata
) |>
  (\(x) x[ , c(1, 2, 5, 8, 3, 6, 9, 4, 7, 10)])() |>
  (\(x)
    {
      x[ , 2:10]  <- round(x[ , 2:10] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Estimate", "95% LCL", "95% UCL"), 3)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Minimal" = 3,
      "Stressed" = 3,
      "Crisis" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

## Livelihood coping strategies index

```{r lcsi, echo = FALSE}
lcsi_province_overall <- endline_lcsi_province_table |>
  subset(
    indicator_variable == "lcsi_score",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

lcsi_strata <- endline_lcsi_strata_table |>
  subset(
    indicator_variable == "lcsi_score" & strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

lcsi_study_group <- endline_lcsi_study_group_table |>
  subset(
    indicator_variable == "lcsi_score" & study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   lcsi_province_overall,
#   lcsi_strata,
#   lcsi_study_group
# ) |>
rbind(
  lcsi_province_overall,
  lcsi_strata
) |>
  #(\(x) x[ , c(1, 2, 6, 10, 3, 7, 11, 4, 8, 12, 5, 9, 13)])() |>
  (\(x)
    {
      x[ , 2:4]  <- round(x[ , 2:4], digits = 3)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", c("Estimate", "95% LCL", "95% UCL")),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = FALSE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Mean Livelihoods Coping Strategies Index" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

<br/>

```{r lcsi_province_plot, echo = FALSE, fig.align = "center", fig.width = 10}
endline_lcsi_province_table |>
  subset(
    indicator_category != "Mean"
  ) |>
  dplyr::mutate(
    indicator_category = factor(
      x = indicator_category, levels = c("secure", "stress", "crisis", "emergency")
    ),
    strata = factor(
      x = strata, levels = c("Zambézia", "Nampula", "Overall")
    )
  ) |>
  ggplot(mapping = aes(x = strata, y = estimate * 100, fill = indicator_category)) +
  geom_bar(stat = "identity", position = "stack", width = 0.5) +
  scale_fill_manual(name = "", values = alpha(rev(lcsi_classes), 0.6)) +
  labs(
    title = "Food insecurity status based on livelihoods coping strategies index",
    subtitle = "Proportion of households in Zambézia, Nampula, and overall by livelihood coping strategies index food insecurity categories",
    x = "", y = "%"
  ) +
  theme_mozambique
```

```{r lcsi_strata_plot, echo = FALSE, fig.align = "center", fig.width = 10}
endline_lcsi_strata_table |>
  subset(strata != "Overall" & indicator_category != "Mean") |>
  dplyr::mutate(
    province = ifelse(
      strata %in% c("Monapo", "Nacala-A-Velha", "Ribáuè", "Rest of Nampula"),
      "Nampula", "Zambézia"
    ) |>
      factor(levels = c("Zambézia", "Nampula")),
    strata = factor(
      strata,
      levels = c(
        "Gurúè", "Lugela", "Pebane", "Molumbo", "Rest of Zambézia", 
        "Monapo", "Nacala-A-Velha", "Ribáuè", "Rest of Nampula"
      ),
      labels = c(
        "\nGurúè", "\nLugela", "\nPebane", "\nMolumbo", "Rest of\nZambézia", 
        "\nMonapo", "\nNacala-A-Velha", "\nRibáuè", "Rest of\nNampula"
      )
    ),
    indicator_category = factor(
      x = indicator_category, levels = c("secure", "stress", "crisis", "emergency")
    ),
  ) |>
  ggplot(
    mapping = aes(x = strata, y = estimate * 100, fill = indicator_category)
  ) +
  geom_bar(stat = "identity", position = "stack", width = 0.75) +
  scale_fill_manual(name = "", values = alpha(rev(lcsi_classes), 0.6)) +
  labs(
    title = "Food insecurity status based on livelihoods coping strategies index",
    subtitle = "Proportion of households in Zambézia and Nampula districts by livelihoods coping strategy food insecurity categories",
    x = "", y = "%"
  ) +
  facet_wrap(~province, scales = "free_x") +
  theme_mozambique
```

<br/>

```{r lcsi_class, echo = FALSE}
lcsi_province_overall <- endline_lcsi_province_table |>
  subset(
    indicator_variable != "lcsi_score",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

lcsi_strata <- endline_lcsi_strata_table |>
  subset(
    indicator_variable != "lcsi_score" & strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

lcsi_study_group <- endline_lcsi_study_group_table |>
  subset(
    indicator_variable != "lcsi_score" & study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   lcsi_province_overall,
#   lcsi_strata,
#   lcsi_study_group
# ) |>
rbind(
  lcsi_province_overall,
  lcsi_strata
) |>
  (\(x) x[ , c(1, 2, 6, 10, 3, 7, 11, 4, 8, 12, 5, 9, 13)])() |>
  (\(x)
    {
      x[ , 2:13]  <- round(x[ , 2:13] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Estimate", "95% LCL", "95% UCL"), 4)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Secure" = 3,
      "Stress" = 3,
      "Crisis" = 3,
      "Emergency" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

## Food stocks

```{r food_stocks_province_plot, echo = FALSE, fig.align = "center", fig.width = 10, fig.height = 10}
rbind(
  endline_corn_reserve_province_table,
  endline_rice_reserve_province_table,
  endline_millet_reserve_province_table,
  endline_sorghum_reserve_province_table,
  endline_cassava_reserve_province_table,
  endline_sweet_potato_reserve_province_table,
  endline_legumes_reserve_province_table
) |>
  dplyr::mutate(
    indicator_variable = factor(
      x = indicator_variable,
      levels = c("corn_reserve", "rice_reserve", "millet_reserve",
                 "sorghum_reserve", "cassava_reserve", "sweet_potato_reserve",
                 "legumes_reserve"),
      labels = c(
        "Corn", "Rice", "Millet", "Sorghum", "Cassava", "Sweet Potato", "Legumes"
      )
    ),
    indicator_category = factor(
      x = indicator_category,
      levels = c(
        "Don't know/No response", "Menos de um mês", "1 a 3 meses", 
        "4 a 6 meses", "Mais de 6 meses"
      )
    ),
    strata = factor(
      x = strata,
      levels = c("Zambézia", "Nampula", "Overall")
    )
  ) |>
  ggplot(
    mapping = aes(x = strata, y = estimate * 100, fill = indicator_category)
  ) +
  geom_bar(stat = "identity", position = "stack", width = 0.75) +
  scale_fill_manual(name = "", values = alpha(stock_classes, 0.6)) +
  labs(
    title = "Household food stock amount",
    subtitle = "Proportion of households in Zambézia, Nampula, and overall by food stock amount",
    x = "", y = "%"
  ) +
  facet_wrap(~indicator_variable, ncol = 4) +
  theme_mozambique +
  theme(
    legend.position = "top"
  )
```

```{r food_stocks_strata_plot, echo = FALSE, fig.align = "center", fig.width = 10, fig.height = 18}
rbind(
  endline_corn_reserve_strata_table,
  endline_rice_reserve_strata_table,
  endline_millet_reserve_strata_table,
  endline_sorghum_reserve_strata_table,
  endline_cassava_reserve_strata_table,
  endline_sweet_potato_reserve_strata_table,
  endline_legumes_reserve_strata_table
) |>
  subset(strata != "Overall") |>
  dplyr::mutate(
    province = ifelse(
      strata %in% c("Monapo", "Nacala-A-Velha", "Ribáuè", "Rest of Nampula"),
      "Nampula", "Zambézia"
    ) |>
      factor(levels = c("Zambézia", "Nampula")),
    strata = factor(
      strata,
      levels = c(
        "Gurúè", "Lugela", "Pebane", "Molumbo", "Rest of Zambézia", 
        "Monapo", "Nacala-A-Velha", "Ribáuè", "Rest of Nampula"
      ),
      labels = c(
        "\nGurúè", "\nLugela", "\nPebane", "\nMolumbo", "Rest of\nZambézia", 
        "\nMonapo", "\nNacala-A-Velha", "\nRibáuè", "Rest of\nNampula"
      )
    ),
    indicator_variable = factor(
      x = indicator_variable,
      levels = c("corn_reserve", "rice_reserve", "millet_reserve",
                 "sorghum_reserve", "cassava_reserve", "sweet_potato_reserve",
                 "legumes_reserve"),
      labels = c(
        "Corn", "Rice", "Millet", "Sorghum", "Cassava", "Sweet Potato", "Legumes"
      )
    ),
    indicator_category = factor(
      x = indicator_category,
      levels = c(
        "Don't know/No response", "Menos de um mês", "1 a 3 meses", 
        "4 a 6 meses", "Mais de 6 meses"
      )
    )
  ) |>
  ggplot(
    mapping = aes(x = strata, y = estimate * 100, fill = indicator_category)
  ) +
  geom_bar(stat = "identity", position = "stack", width = 0.75) +
  scale_fill_manual(name = "", values = alpha(stock_classes, 0.6)) +
  labs(
    title = "Household food stock amount",
    subtitle = "Proportion of households in districts of Zambézia and Nampula by food stock amount",
    x = "", y = "%"
  ) +
  facet_grid(
    rows = vars(indicator_variable), 
    cols = vars(province), scales = "free_x"
  ) +
  theme_mozambique +
  theme(
    legend.position = "top"
  )
```

### Corn stocks

```{r corn_stock, echo = FALSE}
corn_stock_province_overall <- endline_corn_reserve_province_table |>
  subset(
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

corn_stock_strata <- endline_corn_reserve_strata_table |>
  subset(
    strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

corn_stock_study_group <- endline_corn_reserve_study_group_table |>
  subset(
    study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   corn_stock_province_overall,
#   corn_stock_strata,
#   corn_stock_study_group
# ) |>
rbind(
  corn_stock_province_overall,
  corn_stock_strata
) |>
  (\(x) x[ , c(1, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15, 6, 11, 16)])() |>
  (\(x)
    {
      x[ , 2:16]  <- round(x[ , 2:16] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Est", "95% LCL", "95% UCL"), 5)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Menos de um mês" = 3,
      "1 a 3 meses" = 3,
      "4 a 6 meses" = 3,
      "Mais de 6 meses" = 3,
      "Don't know/No response" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

### Rice stocks

```{r rice_stock, echo = FALSE}
rice_stock_province_overall <- endline_rice_reserve_province_table |>
  subset(
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

rice_stock_strata <- endline_rice_reserve_strata_table |>
  subset(
    strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

rice_stock_study_group <- endline_rice_reserve_study_group_table |>
  subset(
    study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   rice_stock_province_overall,
#   rice_stock_strata,
#   rice_stock_study_group
# ) |>
rbind(
  rice_stock_province_overall,
  rice_stock_strata
) |>
  (\(x) x[ , c(1, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15, 6, 11, 16)])() |>
  (\(x)
    {
      x[ , 2:16]  <- round(x[ , 2:16] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Est", "95% LCL", "95% UCL"), 5)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Menos de um mês" = 3,
      "1 a 3 meses" = 3,
      "4 a 6 meses" = 3,
      "Mais de 6 meses" = 3,
      "Don't know/No response" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

### Millet stocks

```{r millet_stock, echo = FALSE}
millet_stock_province_overall <- endline_millet_reserve_province_table |>
  subset(
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

millet_stock_strata <- endline_millet_reserve_strata_table |>
  subset(
    strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

millet_stock_study_group <- endline_millet_reserve_study_group_table |>
  subset(
    study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   millet_stock_province_overall,
#   millet_stock_strata,
#   millet_stock_study_group
# ) |>
rbind(
  millet_stock_province_overall,
  millet_stock_strata
) |>
  (\(x) x[ , c(1, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15, 6, 11, 16)])() |>
  (\(x)
    {
      x[ , 2:16]  <- round(x[ , 2:16] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Est", "95% LCL", "95% UCL"), 5)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Menos de um mês" = 3,
      "1 a 3 meses" = 3,
      "4 a 6 meses" = 3,
      "Mais de 6 meses" = 3,
      "Don't know/No response" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

### Sorghum stocks

```{r sorghum_stock, echo = FALSE}
sorghum_stock_province_overall <- endline_sorghum_reserve_province_table |>
  subset(
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

sorghum_stock_strata <- endline_sorghum_reserve_strata_table |>
  subset(
    strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

sorghum_stock_study_group <- endline_sorghum_reserve_study_group_table |>
  subset(
    study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   sorghum_stock_province_overall,
#   sorghum_stock_strata,
#   sorghum_stock_study_group
# ) |>
rbind(
  sorghum_stock_province_overall,
  sorghum_stock_strata
) |>
  (\(x) x[ , c(1, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15, 6, 11, 16)])() |>
  (\(x)
    {
      x[ , 2:16]  <- round(x[ , 2:16] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Est", "95% LCL", "95% UCL"), 5)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Menos de um mês" = 3,
      "1 a 3 meses" = 3,
      "4 a 6 meses" = 3,
      "Mais de 6 meses" = 3,
      "Don't know/No response" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

### Cassava stocks

```{r cassava_stock, echo = FALSE}
cassava_stock_province_overall <- endline_cassava_reserve_province_table |>
  subset(
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

cassava_stock_strata <- endline_cassava_reserve_strata_table |>
  subset(
    strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

cassava_stock_study_group <- endline_cassava_reserve_study_group_table |>
  subset(
    study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   cassava_stock_province_overall,
#   cassava_stock_strata,
#   cassava_stock_study_group
# ) |>
rbind(
  cassava_stock_province_overall,
  cassava_stock_strata
) |>
  (\(x) x[ , c(1, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15, 6, 11, 16)])() |>
  (\(x)
    {
      x[ , 2:16]  <- round(x[ , 2:16] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Est", "95% LCL", "95% UCL"), 5)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Menos de um mês" = 3,
      "1 a 3 meses" = 3,
      "4 a 6 meses" = 3,
      "Mais de 6 meses" = 3,
      "Don't know/No response" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

### Sweet potato stocks

```{r sweet_potato_stock, echo = FALSE}
sweet_potato_stock_province_overall <- endline_sweet_potato_reserve_province_table |>
  subset(
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

sweet_potato_stock_strata <- endline_sweet_potato_reserve_strata_table |>
  subset(
    strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

sweet_potato_stock_study_group <- endline_sweet_potato_reserve_study_group_table |>
  subset(
    study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   sweet_potato_stock_province_overall,
#   sweet_potato_stock_strata,
#   sweet_potato_stock_study_group
# ) |>
rbind(
  sweet_potato_stock_province_overall,
  sweet_potato_stock_strata
) |>
  (\(x) x[ , c(1, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15, 6, 11, 16)])() |>
  (\(x)
    {
      x[ , 2:16]  <- round(x[ , 2:16] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Est", "95% LCL", "95% UCL"), 5)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Menos de um mês" = 3,
      "1 a 3 meses" = 3,
      "4 a 6 meses" = 3,
      "Mais de 6 meses" = 3,
      "Don't know/No response" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

### Legumes stocks

```{r legumes_stock, echo = FALSE}
legumes_stock_province_overall <- endline_legumes_reserve_province_table |>
  subset(
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x)
   {
     rbind(
       x[3, ],
       x[1:2, ]
     )
   }
  )()

legumes_stock_strata <- endline_legumes_reserve_strata_table |>
  subset(
    strata != "Overall",
    select = c(indicator_category, strata, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  )

legumes_stock_study_group <- endline_legumes_reserve_study_group_table |>
  subset(
    study_group != "Overall",
    select = c(indicator_category, study_group, estimate, lcl, ucl)
  ) |>
  tidyr::pivot_wider(
    names_from = indicator_category,
    values_from = c(estimate, lcl, ucl),
    names_sep = "_"
  ) |>
  (\(x) { names(x)[1] <- "strata"; x })()

# rbind(
#   legumes_stock_province_overall,
#   legumes_stock_strata,
#   legumes_stock_study_group
# ) |>
rbind(
  legumes_stock_province_overall,
  legumes_stock_strata
) |>
  (\(x) x[ , c(1, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15, 6, 11, 16)])() |>
  (\(x)
    {
      x[ , 2:16]  <- round(x[ , 2:16] * 100, digits = 1)
      x
    }
  )() |>
  knitr::kable(
    row.names = FALSE,
    col.names = c(" ", rep(c("Est", "95% LCL", "95% UCL"), 5)),
    align = "r"
  ) |>
  kableExtra::kable_paper(
    lightable_options = "striped", full_width = TRUE, font_size = 12
  ) |>
  kableExtra::add_header_above(
    header = c(
      " " = 1, 
      "Menos de um mês" = 3,
      "1 a 3 meses" = 3,
      "4 a 6 meses" = 3,
      "Mais de 6 meses" = 3,
      "Don't know/No response" = 3
    ),
    bold = TRUE
  ) |>
  kableExtra::pack_rows(
    index = c(
      "Overall" = 1,
      "Province" = 2,
      "Districts in Zambezia" = 5, 
      "Districts in Nampula" = 4
    )
  )
```

<br/>
<br/>
