---
title: Zambezia and Nampula Survey
subtitle: Survey Locations
date: "Produced on `r Sys.time()`"
output:
  flexdashboard::flex_dashboard
---

```{r setup, include = FALSE}
suppressPackageStartupMessages(source(here::here("packages.R")))
for (f in list.files(here::here("R"), full.names = TRUE)) source (f)

targets::tar_load(
  c(
    endline_raw_data_sf, endline_data_eas_for_checking, 
    endline_raw_data_check_sf, baseline_raw_data_sf,
    survey_provinces, survey_districts, survey_posts
  )
)
```

```{r locations-map, echo = FALSE}
leaflet(width = "100%", height = "100%", padding = 0) |>
  addMapboxTiles(
    style_id = "ckk7geu550d8k17l1t39f1t43",
    username = "ernestguevarra"
  ) |>
  setView(
    lng = mean(sf::st_bbox(endline_raw_data_sf)[c(1, 3)]), 
    lat = mean(sf::st_bbox(endline_raw_data_sf)[c(2, 4)]),
    zoom = 8
  ) |>
  addPolygons(
    data = survey_provinces,
    fill = FALSE,
    weight = 5,
    opacity = 1,
    color = "orange",
    group = "Survey provinces"
  ) |>
  addPolygons(
    data = survey_districts,
    fill = FALSE,
    weight = 3,
    opacity = 1,
    color = "orange",
    group = "Survey districts"
  ) |>
  addPolygons(
    data = survey_posts,
    fill = TRUE,
    fillColor = "orange",
    fillOpacity = 0,
    weight = 1,
    opacity = 1,
    color = "orange",
    label = ~paste0(
      "Province: ", ADM1_PT, "<br/>", 
      "District: ", ADM2_PT, "<br/>",
      "Post: ", ADM3_PT, "<br/>"
    ) |>
      lapply(htmltools::HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "12px",
      direction = "auto"
    ),
    group = "Survey posts"
  ) |>
  addCircleMarkers(
    data = baseline_raw_data_sf,
    radius = 5,
    fillColor = "purple",
    weight = 1,
    opacity = 1,
    color = "purple",
    fillOpacity = 0.5,
    label = ~paste0(
      "Baseline location<br/>EA ID: ", enum1
    ) |>
      lapply(htmltools::HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "bold", padding = "3px 8px"),
      textsize = "16px",
      direction = "auto"
    ),
    #clusterOptions = markerClusterOptions(),
    group = "Baseline survey locations"
  ) |>
  addCircleMarkers(
    data = endline_raw_data_sf,
    radius = 5,
    fillColor = "yellow",
    weight = 1,
    opacity = 1,
    color = "yellow",
    fillOpacity = 0.5,
    label = ~paste0(
      "Survey location<br/>FGH_ID: ", fgh_id, "<br/>",
      "Survey date: ", today, "<br/>",
      "Record ID: ", id, "<br/>",
      "Child ID: ", child_id
    ) |>
      lapply(htmltools::HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "bold", padding = "3px 8px"),
      textsize = "16px",
      direction = "auto"
    ),
    #clusterOptions = markerClusterOptions(),
    group = "Endline survey locations"
  ) |>
  addCircleMarkers(
    data = endline_raw_data_check_sf,
    radius = 5,
    fillColor = "red",
    weight = 1,
    opacity = 1,
    color = "red",
    fillOpacity = 0.5,
    label = ~paste0(
      "Check location<br/>FGH_ID: ", fgh_id, "<br/>",
      "Survey date: ", today, "<br/>",
      "Record ID: ", id, "<br/>",
      "Child ID: ", child_id
    ) |>
      lapply(htmltools::HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "bold", padding = "3px 8px"),
      textsize = "16px",
      direction = "auto"
    ),
    #clusterOptions = markerClusterOptions(),
    group = "Endline check locations"
  ) |>
  addLayersControl(
    baseGroups = c(
      "Survey provinces", "Survey districts", "Survey posts"
    ),
    overlayGroups = c(
      "Baseline survey locations",
      "Endline survey locations", 
      "Endline check locations"
    ),
    position = "topright",
    options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
  ) |>
  htmlwidgets::onRender("
    function(el, x) {
      this.on('baselayerchange', function(e) {
        e.layer.bringToBack();
      })
    }
  ")
```